In [1]:
import numpy as np

# Basics

In [2]:
A = np.array([1,2,3])

In [3]:
for e in A:
    print(e)

1
2
3


In [4]:
#Plus sign does vector addition
A+A

array([2, 4, 6])

In [5]:
2*A

array([2, 4, 6])

In [6]:
A**2

array([1, 4, 9])

In [7]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [8]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [9]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

# Dot Product

In [13]:
a = np.array([1,4])
b = np.array([2,1])

In [14]:
dot=0
for e,f in zip(a,b):
    dot+= e*f
dot

6

In [16]:
#Element wise multlipication
a*b

array([2, 4])

In [17]:
np.sum(a*b)

6

In [18]:
(a*b).sum()

6

In [19]:
#actual dot
np.dot(a,b)

6

In [20]:
a.dot(b)

6

In [21]:
b.dot(a)

6

In [23]:
amag = np.linalg.norm(a)
amag

4.123105625617661

# Vectors and Matrices

In [34]:
M= np.array([ [1,2],[3,4] ])
M

array([[1, 2],
       [3, 4]])

In [26]:
M[0][0]

1

In [27]:
M[0,0]

1

In [28]:
M2=np.matrix([ [1,2],[3,4] ])

In [29]:
M2

matrix([[1, 2],
        [3, 4]])

In [30]:
# if you see a matrix, it's a good idea to convert it into an array

In [31]:
A=np.array(M2)

In [33]:
#Transpose of it
A.T

array([[1, 3],
       [2, 4]])

# Creating Arrays

In [36]:
z=np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [39]:
z= np.zeros((3,4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
o = np.ones((2,5))
o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
R= np.random.random((4,4))
R
#All vaues are between zero and  one

array([[0.72321147, 0.83804477, 0.29799058, 0.53583934],
       [0.11411177, 0.72851804, 0.17329648, 0.21873232],
       [0.47416474, 0.57504351, 0.82483198, 0.04426332],
       [0.55478194, 0.9818606 , 0.42953086, 0.69185218]])

In [47]:
#Gaussian distribution doesn't take in a tuple
G = np.random.randn(6,4)
G

array([[-1.94945663, -1.02477029,  0.28226941,  1.0970406 ],
       [ 0.5611131 ,  1.30706889,  1.72468411, -0.03586203],
       [-1.70031529,  0.11006898,  0.63280042,  0.76673511],
       [ 2.01680816,  1.22068793,  0.47837723, -0.61625554],
       [-0.60297832,  0.03624889,  0.46944254,  0.894955  ],
       [-1.17698391, -1.26528871, -1.76270519, -0.94521387]])

In [48]:
G.mean()

0.021602940715770135

In [49]:
G.var()

1.2313477734871434

In [50]:
#Some more functions

In [51]:
A=np.array([[1,2],[3,4]])
Ainv=np.linalg.inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [52]:
#checking
Ainv.dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [53]:
#determinant
np.linalg.det(A)

-2.0000000000000004

In [54]:
#Diagnol
np.diag(A)

array([1, 4])

In [55]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

In [56]:
#Outer Product
a=np.array([1,2])
b=np.array([3,4])

In [57]:
np.outer(a,b)

array([[3, 4],
       [6, 8]])

In [58]:
np.inner(a,b)

11

In [59]:
#sum of diagonals of a matrix
np.trace(A)

5

In [60]:
#eigenvalues and Eigenvectors
X= np.random.randn(100,3)

In [63]:
#covariance of a matrix (don't forget to transpose it)
cov =np.cov(X.T)

In [62]:
cov.shape

(3, 3)

In [64]:
np.linalg.eigh(cov)

(array([0.81525141, 1.09595589, 1.38953438]),
 array([[ 0.12226269, -0.91146637, -0.39278605],
        [-0.03517367,  0.39152732, -0.91949398],
        [ 0.99187431,  0.12623553,  0.01580957]]))

In [65]:
np.linalg.eig(cov)

(array([1.38953438, 1.09595589, 0.81525141]),
 array([[ 0.39278605,  0.91146637,  0.12226269],
        [ 0.91949398, -0.39152732, -0.03517367],
        [-0.01580957, -0.12623553,  0.99187431]]))

# Solving a linear system

In [66]:
# Ax = B
# x = inv.(A)*B

In [67]:
A

array([[1, 2],
       [3, 4]])

In [70]:
b=np.array([1,2])
b

array([1, 2])

In [72]:
x=np.linalg.inv(A).dot(b)
x

array([0. , 0.5])

In [74]:
#never use inverse, always 'solve'. it's more effiecient
x= np.linalg.solve(A,b)
x

array([0. , 0.5])

In [77]:
#Example Problem
A=np.array([[1,1],[1.5,4]])
b=np.array([2200,5050])

np.linalg.solve(A,b)

array([1500.,  700.])